mode = "dark"
fg = "#c0caf5"
bg = "#1a1b26"
bg0 = "#111118"
accent = "#7aa2f7"
cursor = "#c0caf5"
cursor_text = "#1a1b26"
fg_selection = "#c0caf5"
bg_selection = "#283457"

c0 =  "#15161e"
c1 =  "#f7768e"
c2 =  "#9ece6a"
c3 =  "#e0af68"
c4 =  "#7aa2f7"
c5 =  "#bb9af7"
c6 =  "#7dcfff"
c7 =  "#a9b1d6"
c8 =  "#414868"
c9 =  "#f7768e"
c10 = "#9ece6a"
c11 = "#e0af68"
c12 = "#7aa2f7"
c13 = "#bb9af7"
c14 = "#7dcfff"
c15 = "#c0caf5"

thickness = 1
rounding = 0
spacing = 18

[opacity]
active = 1
inactive = 1
