~/.config/kitty/zenkai.conf :: pkill -SIGUSR1 kitty
foreground {{ fg }}
background {{ bg }}
cursor {{ cursor }}
cursor_text {{ cursor_text }}
inactive_border_color {{ bg0 }}
active_border_color {{ accent }}
selection_foreground {{ fg_selection }}
selection_background {{ bg_selection }}

color0  {{ c0 }}
color1  {{ c1 }}
color2  {{ c2 }}
color3  {{ c3 }}
color4  {{ c4 }}
color5  {{ c5 }}
color6  {{ c6 }}
color7  {{ c7 }}
color8  {{ c8 }}
color9  {{ c9 }}
color10 {{ c10 }}
color11 {{ c11 }}
color12 {{ c12 }}
color13 {{ c13 }}
color14 {{ c14 }}
color15 {{ c15 }}
