~/.local/share/vicinae/themes/zenkai.toml :: vicinae theme set zenkai
[meta]
name = "Catppuccin Mocha"
description = ""
variant = "dark"

[colors.core]
background = "{{ bg }}"
foreground = "{{ fg }}"
secondary_background = "{{ bg0 }}"
border = "{{ c0 }}"
accent = "{{ accent }}"

[colors.accents]
blue = "{{ c4 }}"
green = "{{ c2 }}"
magenta = "{{ c5 }}"
orange = "#FAB387"
purple = "#CBA6F7"
red = "{{ c1 }}"
yellow = "{{ c3 }}"
cyan = "{{ c6 }}"

[colors.list.item.selection]
background = "{{ bg_selection }}"
secondary_background = "{{ c0 }}"
foreground = "{{ fg_selection }}"

[colors.list.item.hover]
background = { name = "{{ bg0 }}", opacity = 0.1 }
foreground = "{{ fg }}"
